# Run test suite.
#
# $Id: Makefile 2626 2007-03-09 04:35:54Z andrewm $
# $Source: /usr/local/cvsroot/NSWDoH/SOOMv0/soomext/test/Makefile,v $

PYTHON=PYTHONPATH=.. python

all:
	$(PYTHON) all.py

clean:
	rm -rf *.pyc
