#
#   The contents of this file are subject to the HACOS License Version 1.2
#   (the "License"); you may not use this file except in compliance with
#   the License.  Software distributed under the License is distributed
#   on an "AS IS" basis, WITHOUT WARRANTY OF ANY KIND, either express or
#   implied. See the LICENSE file for the specific language governing
#   rights and limitations under the License.  The Original Software
#   is "NetEpi Analysis". The Initial Developer of the Original
#   Software is the Health Administration Corporation, incorporated in
#   the State of New South Wales, Australia.
#
#   Copyright (C) 2004,2005 Health Administration Corporation. 
#   All Rights Reserved.
#
#
# $Id: install.py 2626 2007-03-09 04:35:54Z andrewm $
# $Source: /usr/local/cvsroot/NSWDoH/SOOMv0/web/install.py,v $

import sys, os
parent_dir = os.path.normpath(os.path.join(os.path.dirname(__file__), '..'))
sys.path.insert(0, parent_dir)
from simpleinst import *

config.appname = 'nea'
config.apptitle = 'NetEpi-Analysis'
config.install_owner = 'root'
config.install_exclude = 'CVS'
config.soompath = 'SOOM_objects'
config.session_secret = secret()

# script_dir contains application and libraries
config.script_dir = joinpath(config.cgi_dir, config.appname)

# data_dir is a directory writeable by the web user, but NOT PUBLISHED
# by the web server (contains confidential data)
config.data_dir = joinpath(config.cgi_dir, config.appname, 'data')

# static_target contains content that does not change, such as images and
# style sheets. This directory should be published by the web server

config.static_target = joinpath(config.html_dir, config.appname)

# dynamic_target contains content that is generated by the application and is
# intended to be published by the web server.
config.dynamic_target = joinpath(config.html_dir, config.appname, 'dynamic')

config_attrs = (
    'appname', 'apptitle', 'session_secret',
    'data_dir', 'static_target', 'dynamic_target', 'soompath',
)

config.config_owner = '%s:%s' % (config.install_owner, 
                                 user_lookup(config.web_user)[1])
config.write_file(joinpath(config.script_dir, 'config.py'),
                  config_attrs, owner = config.config_owner, mode = 0640)

on_install('*.py', py_compile)

# Sundry static content
install(target = config.static_target, 
        base = 'static', files = ['style.css', '*.png', '*.html'])

# App modules and pages
install(target = config.script_dir, 
        files = ['pages', 'libsoomexplorer'], 
        include = ['*.py', '*.html'])

# Application
install(target = config.script_dir, 
        filter = python_bang_path_filter,
        files = 'nea.py', mode = 0755)

make_dirs(config.data_dir, owner=config.web_user)
make_dirs(config.dynamic_target, owner=config.web_user)
